blank_issues_enabled: true
contact_links:
  - name: Ocre Community
    url: https://lfedge.slack.com/archives/C07F190CC3X
    about: Join our Slack channel for quick questions and community discussions
