name: Tests
on:
    push:
      branches:
          - feature/add-testing-framework
    pull_request:
        branches:
            - feature/add-testing-framework
jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
      
            - name: Flash Validation Tests
              run: |
                  cd tests && bash beginTests.sh "flashValidation" && cat /tmp/flashValidation.log
            
            - name: Upload log file as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: "FlashValidation.log"
                  path: /tmp/flashValidation.log
