name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
    tests:
        runs-on: zephyr-xlarge-runner

        steps:
            - name: Make the github actions runner recursively take ownership of the github workspace
              run: sudo chown -R $(whoami) ${{ github.workspace }}

            - name: Checkout
              uses: actions/checkout@v4
      
            - name: Flash Validation Tests
              run: |
                  cd tests && bash beginTests.sh "flashValidation"

            - name: Print Flash Validation Logs
              if: always()
              run: cat /tmp/flashValidation.log
            
            - name: Upload log file as artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: "FlashValidation.log"
                  path: /tmp/flashValidation.log
