name: Tests
on:
    push:
      branches:
          - main
    pull_request:
        branches:
            - main
jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
      
            - name: Flash Validation Tests
              run: |
                  bash beginTests.sh "flashValidation"
